### ISSUE TITLE
team-99 peer-to-peer code review

### ISSUE THREAD

**Issue by JelilFaisalAbudu** [NiiazalyDzhumaliev/newsweek-bootstrap#1]
- you are really doing well.
- But remember to follow all the requirements so as to avoid issues with TSEs.

**Comment by DickensJuma** [comment]
- please try to avoid padding and margin

- Use bootstrap as much as possible

**Comment by NiiazalyDzhumaliev** [comment]
I used bootstrap classes to make the margin and padding
